services:
    commerce.handler.create_order_status:
        class: Backend\Modules\Commerce\Domain\OrderStatus\Command\CreateOrderStatusHandler
        arguments:
            - "@commerce.repository.order_status"
        tags:
            - { name: command_handler, handles: Backend\Modules\Commerce\Domain\OrderStatus\Command\CreateOrderStatus }

    commerce.handler.update_order_status:
        class: Backend\Modules\Commerce\Domain\OrderStatus\Command\UpdateOrderStatusHandler
        arguments:
            - "@commerce.repository.order_status"
        tags:
            - { name: command_handler, handles: Backend\Modules\Commerce\Domain\OrderStatus\Command\UpdateOrderStatus }

    commerce.handler.delete_order_status:
        class: Backend\Modules\Commerce\Domain\OrderStatus\Command\DeleteOrderStatusHandler
        arguments:
            - "@commerce.repository.order_status"
        tags:
            - { name: command_handler, handles: Backend\Modules\Commerce\Domain\OrderStatus\Command\DeleteOrderStatus }
