services:
  Backend\Modules\Commerce\Domain\Product\ProductSitemapProvider:
    arguments:
      - "@commerce.repository.product"
    tags:
      - { name: sitemap.provider }
  Backend\Modules\Commerce\Domain\Category\CategorySitemapProvider:
    arguments:
      - "@commerce.repository.category"
      - "@fork.settings"
    tags:
      - { name: sitemap.provider }
