services:
    commerce.handler.create_stock_status:
        class: Backend\Modules\Commerce\Domain\StockStatus\Command\CreateStockStatusHandler
        arguments:
            - "@commerce.repository.stock_status"
        tags:
            - { name: command_handler, handles: Backend\Modules\Commerce\Domain\StockStatus\Command\CreateStockStatus }

    commerce.handler.update_stock_status:
        class: Backend\Modules\Commerce\Domain\StockStatus\Command\UpdateStockStatusHandler
        arguments:
            - "@commerce.repository.stock_status"
        tags:
            - { name: command_handler, handles: Backend\Modules\Commerce\Domain\StockStatus\Command\UpdateStockStatus }

    commerce.handler.delete_stock_status:
        class: Backend\Modules\Commerce\Domain\StockStatus\Command\DeleteStockStatusHandler
        arguments:
            - "@commerce.repository.stock_status"
        tags:
            - { name: command_handler, handles: Backend\Modules\Commerce\Domain\StockStatus\Command\DeleteStockStatus }
