services:
    catalog.handler.create_brand:
        class: Backend\Modules\Catalog\Domain\Brand\Command\CreateBrandHandler
        arguments:
            - "@catalog.repository.brand"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Brand\Command\CreateBrand }

    catalog.handler.update_brand:
        class: Backend\Modules\Catalog\Domain\Brand\Command\UpdateBrandHandler
        arguments:
            - "@catalog.repository.brand"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Brand\Command\UpdateBrand }

    catalog.handler.delete_brand:
        class: Backend\Modules\Catalog\Domain\Brand\Command\DeleteBrandHandler
        arguments:
            - "@catalog.repository.brand"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Brand\Command\DeleteBrand }
