services:
    catalog.handler.create_cart_rule:
        class: Backend\Modules\Catalog\Domain\CartRule\Command\CreateCartRuleHandler
        arguments:
            - "@catalog.repository.cart_rule"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\CartRule\Command\CreateCartRule }

    catalog.handler.update_cart_rule:
        class: Backend\Modules\Catalog\Domain\CartRule\Command\UpdateCartRuleHandler
        arguments:
            - "@catalog.repository.cart_rule"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\CartRule\Command\UpdateCartRule }

    catalog.handler.delete_cart_rule:
        class: Backend\Modules\Catalog\Domain\CartRule\Command\DeleteCartRuleHandler
        arguments:
            - "@catalog.repository.cart_rule"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\CartRule\Command\DeleteCartRule }
