services:
    catalog.handler.create_country:
        class: Backend\Modules\Catalog\Domain\Country\Command\CreateCountryHandler
        arguments:
            - "@catalog.repository.country"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Country\Command\CreateCountry }

    catalog.handler.update_country:
        class: Backend\Modules\Catalog\Domain\Country\Command\UpdateCountryHandler
        arguments:
            - "@catalog.repository.country"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Country\Command\UpdateCountry }

    catalog.handler.delete_country:
        class: Backend\Modules\Catalog\Domain\Country\Command\DeleteCountryHandler
        arguments:
            - "@catalog.repository.country"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Country\Command\DeleteCountry }
