doctrine:
  dbal:
    types:
      catalog_category_image_type: Backend\Modules\Catalog\Domain\Category\ImageDBALType
      catalog_brand_image_type: Backend\Modules\Catalog\Domain\Brand\ImageDBALType
  orm:
    mappings:
      category:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Category"
        alias: CatalogCategory
        prefix: Backend\Modules\Catalog\Domain\Category
      product:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Product"
        alias: CatalogProduct
        prefix: Backend\Modules\Catalog\Domain\Product
      brand:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Brand"
        alias: CatalogBrand
        prefix: Backend\Modules\Catalog\Domain\Brand
      order:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Order"
        alias: CatalogOrder
        prefix: Backend\Modules\Catalog\Domain\Order
      order_address:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/OrderAddress"
        alias: CatalogOrderAddress
        prefix: Backend\Modules\Catalog\Domain\OrderAddress
      order_vat:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/OrderVat"
        alias: CatalogOrderVat
        prefix: Backend\Modules\Catalog\Domain\OrderVat
      order_product:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/OrderProduct"
        alias: CatalogOrderProduct
        prefix: Backend\Modules\Catalog\Domain\OrderProduct
      order_history:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/OrderHistory"
        alias: CatalogOrderHistory
        prefix: Backend\Modules\Catalog\Domain\OrderHistory
      specification:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Specification"
        alias: CatalogSpecification
        prefix: Backend\Modules\Catalog\Domain\Specification
      specification_value:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/SpecificationValue"
        alias: CatalogSpecificationValue
        prefix: Backend\Modules\Catalog\Domain\SpecificationValue
      vat:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Vat"
        alias: CatalogVat
        prefix: Backend\Modules\Catalog\Domain\Vat
      product_special:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/ProductSpecial"
        alias: CatalogProductSpecial
        prefix: Backend\Modules\Catalog\Domain\ProductSpecial
      stock_status:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/StockStatus"
        alias: CatalogStockStatus
        prefix: Backend\Modules\Catalog\Domain\StockStatus
      cart:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Cart"
        alias: CatalogCart
        prefix: Backend\Modules\Catalog\Domain\Cart
      shipment_method:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/ShipmentMethod"
        alias: CatalogShipmentMethod
        prefix: Backend\Modules\Catalog\Domain\ShipmentMethod
      payment_method:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/PaymentMethod"
        alias: CatalogPaymentMethod
        prefix: Backend\Modules\Catalog\Domain\PaymentMethod
      product_option:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/ProductOption"
        alias: CatalogProductOption
        prefix: Backend\Modules\Catalog\Domain\ProductOption
      product_option_value:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/ProductOptionValue"
        alias: CatalogProductOption
        prefix: Backend\Modules\Catalog\Domain\ProductOptionValue
      catalog_up_sell_product:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/UpSellProduct"
        alias: CatalogUpSellProduct
        prefix: Backend\Modules\Catalog\Domain\UpSellProduct
