doctrine:
  dbal:
    types:
      catalog_category_image_type: Backend\Modules\Catalog\Domain\Category\ImageDBALType
      catalog_brand_image_type: Backend\Modules\Catalog\Domain\Brand\ImageDBALType
  orm:
    mappings:
      catalog_category:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Category"
        alias: CatalogCategory
        prefix: Backend\Modules\Catalog\Domain\Category
      catalog_product:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Product"
        alias: CatalogProduct
        prefix: Backend\Modules\Catalog\Domain\Product
      catalog_brand:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Brand"
        alias: CatalogBrand
        prefix: Backend\Modules\Catalog\Domain\Brand
      catalog_order:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Order"
        alias: CatalogOrder
        prefix: Backend\Modules\Catalog\Domain\Order
      catalog_order_address:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/OrderAddress"
        alias: CatalogOrderAddress
        prefix: Backend\Modules\Catalog\Domain\OrderAddress
      catalog_order_vat:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/OrderVat"
        alias: CatalogOrderVat
        prefix: Backend\Modules\Catalog\Domain\OrderVat
      catalog_order_product:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/OrderProduct"
        alias: CatalogOrderProduct
        prefix: Backend\Modules\Catalog\Domain\OrderProduct
      catalog_order_product_option:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/OrderProductOption"
        alias: CatalogOrderProductOption
        prefix: Backend\Modules\Catalog\Domain\OrderProductOption
      catalog_order_product_notification:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/OrderProductNotification"
        alias: CatalogOrderProductNotification
        prefix: Backend\Modules\Catalog\Domain\OrderProductNotification
      catalog_order_history:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/OrderHistory"
        alias: CatalogOrderHistory
        prefix: Backend\Modules\Catalog\Domain\OrderHistory
      catalog_order_status:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/OrderStatus"
        alias: CatalogOrderStatus
        prefix: Backend\Modules\Catalog\Domain\OrderStatus
      catalog_order_rule:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/OrderRule"
        alias: CatalogOrderRule
        prefix: Backend\Modules\Catalog\Domain\OrderRule
      catalog_specification:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Specification"
        alias: CatalogSpecification
        prefix: Backend\Modules\Catalog\Domain\Specification
      catalog_specification_value:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/SpecificationValue"
        alias: CatalogSpecificationValue
        prefix: Backend\Modules\Catalog\Domain\SpecificationValue
      catalog_vat:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Vat"
        alias: CatalogVat
        prefix: Backend\Modules\Catalog\Domain\Vat
      catalog_country:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Country"
        alias: CatalogCountry
        prefix: Backend\Modules\Catalog\Domain\Country
      catalog_stock_status:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/StockStatus"
        alias: CatalogStockStatus
        prefix: Backend\Modules\Catalog\Domain\StockStatus
      catalog_cart:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Cart"
        alias: CatalogCart
        prefix: Backend\Modules\Catalog\Domain\Cart
      catalog_cart_rule:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/CartRule"
        alias: CatalogCartRule
        prefix: Backend\Modules\Catalog\Domain\CartRule
      catalog_shipment_method:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/ShipmentMethod"
        alias: CatalogShipmentMethod
        prefix: Backend\Modules\Catalog\Domain\ShipmentMethod
      catalog_payment_method:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/PaymentMethod"
        alias: CatalogPaymentMethod
        prefix: Backend\Modules\Catalog\Domain\PaymentMethod
      catalog_product_dimension:
          type: annotation
          is_bundle: false
          dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/ProductDimension"
          alias: CatalogProductDimension
          prefix: Backend\Modules\Catalog\Domain\ProductDimension
      catalog_product_dimension_notification:
          type: annotation
          is_bundle: false
          dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/ProductDimensionNotification"
          alias: CatalogProductDimensionNotification
          prefix: Backend\Modules\Catalog\Domain\ProductDimensionNotification
      catalog_product_option:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/ProductOption"
        alias: CatalogProductOption
        prefix: Backend\Modules\Catalog\Domain\ProductOption
      catalog_product_option_value:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/ProductOptionValue"
        alias: CatalogProductOption
        prefix: Backend\Modules\Catalog\Domain\ProductOptionValue
      catalog_product_special:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/ProductSpecial"
        alias: CatalogProductSpecial
        prefix: Backend\Modules\Catalog\Domain\ProductSpecial
      catalog_catalog_up_sell_product:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/UpSellProduct"
        alias: CatalogUpSellProduct
        prefix: Backend\Modules\Catalog\Domain\UpSellProduct
      catalog_account:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Backend/Modules/Catalog/Domain/Account"
        alias: CatalogAccount
        prefix: Backend\Modules\Catalog\Domain\Account
