services:
    catalog.handler.create_order:
        class: Backend\Modules\Catalog\Domain\Order\Command\CreateOrderHandler
        arguments:
            - "@catalog.repository.order"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Order\Command\CreateOrder }

    catalog.handler.update_order:
        class: Backend\Modules\Catalog\Domain\Order\Command\UpdateOrderHandler
        arguments:
            - "@catalog.repository.order"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Order\Command\UpdateOrder }

    catalog.handler.delete_order:
        class: Backend\Modules\Catalog\Domain\Order\Command\DeleteOrderHandler
        arguments:
            - "@catalog.repository.order"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Order\Command\DeleteOrder }
