services:
    catalog.handler.create_order_status:
        class: Backend\Modules\Catalog\Domain\OrderStatus\Command\CreateOrderStatusHandler
        arguments:
            - "@catalog.repository.order_status"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderStatus\Command\CreateOrderStatus }

    catalog.handler.update_order_status:
        class: Backend\Modules\Catalog\Domain\OrderStatus\Command\UpdateOrderStatusHandler
        arguments:
            - "@catalog.repository.order_status"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderStatus\Command\UpdateOrderStatus }

    catalog.handler.delete_order_status:
        class: Backend\Modules\Catalog\Domain\OrderStatus\Command\DeleteOrderStatusHandler
        arguments:
            - "@catalog.repository.order_status"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\OrderStatus\Command\DeleteOrderStatus }
