services:
    catalog.event.order_created:
        class: Backend\Modules\Catalog\Domain\Order\EventListener\OrderCreated
        arguments:
            - "@mailer"
            - "@fork.settings"
        tags:
            - { name: kernel.event_listener, event: catalog.event.order.created, method: onOrderCreated }
    catalog.event.order_updated:
        class: Backend\Modules\Catalog\Domain\Order\EventListener\OrderUpdated
        arguments:
            - "@mailer"
            - "@fork.settings"
        tags:
            - { name: kernel.event_listener, event: catalog.event.order.updated, method: onOrderUpdated }
