services:
    catalog.handler.create_product:
        class: Backend\Modules\Catalog\Domain\Product\Command\CreateProductHandler
        arguments:
            - "@catalog.repository.product"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Product\Command\CreateProduct }

    catalog.handler.update_product:
        class: Backend\Modules\Catalog\Domain\Product\Command\UpdateProductHandler
        arguments:
            - "@catalog.repository.product"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Product\Command\UpdateProduct }

    catalog.handler.delete_product:
        class: Backend\Modules\Catalog\Domain\Product\Command\DeleteProductHandler
        arguments:
            - "@catalog.repository.product"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Product\Command\DeleteProduct }

    catalog.form.product_validation_resolver:
        class: Backend\Modules\Catalog\Domain\Product\ValidationGroupResolver
