services:
    catalog.handler.create_product_option:
        class: Backend\Modules\Catalog\Domain\ProductOption\Command\CreateProductOptionHandler
        arguments:
            - "@catalog.repository.product_option"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\ProductOption\Command\CreateProductOption }

    catalog.handler.update_product_option:
        class: Backend\Modules\Catalog\Domain\ProductOption\Command\UpdateProductOptionHandler
        arguments:
            - "@catalog.repository.product_option"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\ProductOption\Command\UpdateProductOption }

    catalog.handler.delete_product_option:
        class: Backend\Modules\Catalog\Domain\ProductOption\Command\DeleteProductOptionHandler
        arguments:
            - "@catalog.repository.product_option"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\ProductOption\Command\DeleteProductOption }
