services:
    catalog.handler.create_product_option_value:
        class: Backend\Modules\Catalog\Domain\ProductOptionValue\Command\CreateProductOptionValueHandler
        arguments:
            - "@catalog.repository.product_option_value"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\ProductOptionValue\Command\CreateProductOptionValue }

    catalog.handler.update_product_option_value:
        class: Backend\Modules\Catalog\Domain\ProductOptionValue\Command\UpdateProductOptionValueHandler
        arguments:
            - "@catalog.repository.product_option_value"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\ProductOptionValue\Command\UpdateProductOptionValue }

    catalog.handler.delete_product_option_value:
        class: Backend\Modules\Catalog\Domain\ProductOptionValue\Command\DeleteProductOptionValueHandler
        arguments:
            - "@catalog.repository.product_option_value"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\ProductOptionValue\Command\DeleteProductOptionValue }
