services:
    catalog.event.quote_created:
        class: Backend\Modules\Catalog\Domain\Quote\EventListener\QuoteCreated
        arguments:
            - "@mailer"
            - "@fork.settings"
        tags:
            - { name: kernel.event_listener, event: catalog.event.quote.created, method: onQuoteCreated }
