services:
    catalog.repository.category:
        class: Backend\Modules\Catalog\Domain\Category\CategoryRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\Category\Category

    catalog.repository.product:
        class: Backend\Modules\Catalog\Domain\Product\ProductRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\Product\Product

    catalog.repository.brand:
        class: Backend\Modules\Catalog\Domain\Brand\BrandRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\Brand\Brand

    catalog.repository.order:
        class: Backend\Modules\Catalog\Domain\Order\OrderRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\Order\Order

    catalog.repository.order_product:
        class: Backend\Modules\Catalog\Domain\OrderProduct\OrderProductRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\OrderProduct\OrderProduct

    catalog.repository.order_product_option:
        class: Backend\Modules\Catalog\Domain\OrderProductOption\OrderProductOptionRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\OrderProductOption\OrderProductOption

    catalog.repository.order_product_notification:
        class: Backend\Modules\Catalog\Domain\OrderProductNotification\OrderProductNotificationRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\OrderProductNotification\OrderProductNotification

    catalog.repository.order_address:
        class: Backend\Modules\Catalog\Domain\OrderAddress\OrderAddressRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\OrderAddress\OrderAddress

    catalog.repository.order_vat:
        class: Backend\Modules\Catalog\Domain\OrderVat\OrderVatRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\OrderVat\OrderVat

    catalog.repository.order_status:
        class: Backend\Modules\Catalog\Domain\OrderStatus\OrderStatusRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\OrderStatus\OrderStatus

    catalog.repository.order_history:
        class: Backend\Modules\Catalog\Domain\OrderHistory\OrderHistoryRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\OrderHistory\OrderHistory

    catalog.repository.order_rule:
        class: Backend\Modules\Catalog\Domain\OrderRule\OrderRuleRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\OrderRule\OrderRule

    catalog.repository.specification:
        class: Backend\Modules\Catalog\Domain\Specification\SpecificationRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\Specification\Specification

    catalog.repository.specification_value:
        class: Backend\Modules\Catalog\Domain\SpecificationValue\SpecificationValueRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\SpecificationValue\SpecificationValue

    catalog.repository.vat:
        class: Backend\Modules\Catalog\Domain\Vat\VatRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\Vat\Vat

    catalog.repository.country:
        class: Backend\Modules\Catalog\Domain\Country\CountryRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\Country\Country

    catalog.repository.stock_status:
        class: Backend\Modules\Catalog\Domain\StockStatus\StockStatusRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\StockStatus\StockStatus

    catalog.repository.cart:
        class: Backend\Modules\Catalog\Domain\Cart\CartRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\Cart\Cart

    catalog.repository.cart_rule:
        class: Backend\Modules\Catalog\Domain\CartRule\CartRuleRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\CartRule\CartRule

    catalog.repository.cart_value:
        class: Backend\Modules\Catalog\Domain\Cart\CartValueRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\Cart\CartValue

    catalog.repository.cart_value_option:
        class: Backend\Modules\Catalog\Domain\Cart\CartValueOptionRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\Cart\CartValueOption

    catalog.repository.shipment_method:
        class: Backend\Modules\Catalog\Domain\ShipmentMethod\ShipmentMethodRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\ShipmentMethod\ShipmentMethod

    catalog.repository.payment_method:
        class: Backend\Modules\Catalog\Domain\PaymentMethod\PaymentMethodRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\PaymentMethod\PaymentMethod

    catalog.repository.product_option:
        class: Backend\Modules\Catalog\Domain\ProductOption\ProductOptionRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\ProductOption\ProductOption

    catalog.repository.product_option_value:
        class: Backend\Modules\Catalog\Domain\ProductOptionValue\ProductOptionValueRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\ProductOptionValue\ProductOptionValue

    catalog.repository.product_dimension:
        class: Backend\Modules\Catalog\Domain\ProductDimension\ProductDimensionRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\ProductDimension\ProductDimension

    catalog.repository.up_sell_product:
        class: Backend\Modules\Catalog\Domain\UpSellProduct\UpSellProductRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\UpSellProduct\UpSellProduct

    catalog.repository.account:
        class: Backend\Modules\Catalog\Domain\Account\AccountRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\Catalog\Domain\Account\Account
