services:
    catalog.handler.create_specification:
        class: Backend\Modules\Catalog\Domain\Specification\Command\CreateSpecificationHandler
        arguments:
            - "@catalog.repository.specification"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Specification\Command\CreateSpecification }

    catalog.handler.update_specification:
        class: Backend\Modules\Catalog\Domain\Specification\Command\UpdateSpecificationHandler
        arguments:
            - "@catalog.repository.specification"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Specification\Command\UpdateSpecification }

    catalog.handler.delete_specification:
        class: Backend\Modules\Catalog\Domain\Specification\Command\DeleteSpecificationHandler
        arguments:
            - "@catalog.repository.specification"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Specification\Command\DeleteSpecification }
