services:
    catalog.handler.create_vat:
        class: Backend\Modules\Catalog\Domain\Vat\Command\CreateVatHandler
        arguments:
            - "@catalog.repository.vat"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Vat\Command\CreateVat }

    catalog.handler.update_vat:
        class: Backend\Modules\Catalog\Domain\Vat\Command\UpdateVatHandler
        arguments:
            - "@catalog.repository.vat"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Vat\Command\UpdateVat }

    catalog.handler.delete_vat:
        class: Backend\Modules\Catalog\Domain\Vat\Command\DeleteVatHandler
        arguments:
            - "@catalog.repository.vat"
        tags:
            - { name: command_handler, handles: Backend\Modules\Catalog\Domain\Vat\Command\DeleteVat }
