on:
  push:
    branches: [master]

name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Activate Namespace
        uses: okteto/namespace@master
        with:
          namespace: jessedobbelaere

      - name: Deploy Pipeline
        uses: okteto/pipeline@master
        with:
          name: fork-cms-module-commerce-demo
          timeout: 8m
